import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footetr from "@/components/Footetr";
import SessionWrapper from "./component/SessionWrapper";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata = {
  title: "Educate-One ✔",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className=" min-h-[77vh] [background:radial-gradient(125%_125%_at_55%_57%,#000_40%,#63e_100%)] text-white " >
        <Navbar/>
        {children}
     </div>
        <Footetr/>
      </body>
      </SessionWrapper>
    </html>
  );
}